name: Lint

on:
  push:
    paths:
      - '*.py'

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.11.7
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1.3
        with:
          checkName: 'mypy'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.11.7
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install ruff
        run: pip install ruff
      - name: Ruff Check
        uses: jpetrucciani/ruff-check@0.1.0
        with:
          path: '.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.11.7
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install flake8
        run: pip install flake8
      - name: Flake8 action
        uses: suo/flake8-github-action@v1
        with:
          checkName: 'flake8'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
