name: Lint

on:
  push:
    paths:
      - '*.py'

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.11.7
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: |
          flake8 . --count --show-source --statistics
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.11.7
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        run: |
          mypy .
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.11.7
      - name: Install ruff
        run: pip install ruff
      - name: Run ruff
        run: |
          ruff check . --output-format github
